FROM node:18.15.0-alpine3.17

WORKDIR /app

ADD package.json package-lock.json ./

RUN npm install

ADD .eslintrc.cjs .prettierrc.json env.d.ts index.html tsconfig.config.json tsconfig.json vite.config.ts ./

CMD ["npm", "run", "dev"]
